# версия docker-compose
version: '3.7'

services:
  hh_parser_bot:
    image: hh_parser_bot_image
    container_name: hh_parser_bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env

